// <auto-generated />
using System;
using MedRateSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedRateSystem.Migrations
{
    [DbContext(typeof(MedRateContext))]
    [Migration("20260609153852_ThemTieuChiDanhGia")]
    partial class ThemTieuChiDanhGia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedRateSystem.Models.BenhNhan", b =>
                {
                    b.Property<string>("MaBenhNhan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MaBenhNhan")
                        .HasName("PK__BenhNhan__22A8B330A7903BBE");

                    b.ToTable("BenhNhan", (string)null);
                });

            modelBuilder.Entity("MedRateSystem.Models.ChiTietDonThuoc", b =>
                {
                    b.Property<string>("MaDonThuoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaThuoc")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CachDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("ThuocMaThuoc")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaDonThuoc", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.HasIndex("ThuocMaThuoc");

                    b.ToTable("ChiTietDonThuoc", (string)null);
                });

            modelBuilder.Entity("MedRateSystem.Models.ChiTietKhaoSat", b =>
                {
                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<string>("MaThuoc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("CoTacDungPhu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("DiemHieuQua")
                        .HasColumnType("int");

                    b.Property<int>("DiemLikert")
                        .HasColumnType("int");

                    b.Property<int>("DiemTacDungPhu")
                        .HasColumnType("int");

                    b.Property<int>("DiemTienLoi")
                        .HasColumnType("int");

                    b.Property<int>("DiemTongThe")
                        .HasColumnType("int");

                    b.Property<string>("MoTaTrieuChung")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieu", "MaThuoc")
                        .HasName("PK__ChiTietK__32DBA082CEAC313E");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietKhaoSat", (string)null);
                });

            modelBuilder.Entity("MedRateSystem.Models.DonThuoc", b =>
                {
                    b.Property<string>("MaDonThuoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BacSiKeDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBenhNhan")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayKeDon")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDonThuoc");

                    b.HasIndex("MaBenhNhan");

                    b.ToTable("DonThuoc", (string)null);
                });

            modelBuilder.Entity("MedRateSystem.Models.PhieuCanhBaoAdr", b =>
                {
                    b.Property<int>("MaCanhBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCanhBao"));

                    b.Property<bool>("DaXuLy")
                        .HasColumnType("bit");

                    b.Property<string>("MaThuoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayPhatHien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDungCanhBao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("TyLeThucTe")
                        .HasColumnType("float");

                    b.HasKey("MaCanhBao")
                        .HasName("PK__PhieuCan__73C23D934378EE10");

                    b.HasIndex("MaThuoc");

                    b.ToTable("PhieuCanhBaoADR", (string)null);
                });

            modelBuilder.Entity("MedRateSystem.Models.PhieuKhaoSat", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<string>("GhiChuNhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBenhNhan")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ThoiGianLamPhieu")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaBenhNhan");

                    b.ToTable("PhieuKhaoSat", (string)null);
                });

            modelBuilder.Entity("MedRateSystem.Models.Thuoc", b =>
                {
                    b.Property<string>("MaThuoc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("DiemLikertTb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(5.0)
                        .HasColumnName("DiemLikertTB");

                    b.Property<decimal?>("GiaTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaTien");

                    b.Property<string>("NhaSanXuat")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhanLoaiVen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhanLoaiVen");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("TyLeAdr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("TyLeADR");

                    b.HasKey("MaThuoc")
                        .HasName("PK__Thuoc__4BB1F620B5D55177");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("MedRateSystem.Models.ChiTietDonThuoc", b =>
                {
                    b.HasOne("MedRateSystem.Models.DonThuoc", null)
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("MaDonThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedRateSystem.Models.Thuoc", "MaThuocNavigation")
                        .WithMany()
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedRateSystem.Models.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("ThuocMaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaThuocNavigation");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("MedRateSystem.Models.ChiTietKhaoSat", b =>
                {
                    b.HasOne("MedRateSystem.Models.PhieuKhaoSat", "MaPhieuNavigation")
                        .WithMany("ChiTietKhaoSats")
                        .HasForeignKey("MaPhieu")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTiet_Phieu");

                    b.HasOne("MedRateSystem.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("ChiTietKhaoSats")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTiet_Thuoc");

                    b.Navigation("MaPhieuNavigation");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("MedRateSystem.Models.DonThuoc", b =>
                {
                    b.HasOne("MedRateSystem.Models.BenhNhan", "MaBenhNhanNavigation")
                        .WithMany()
                        .HasForeignKey("MaBenhNhan")
                        .HasConstraintName("FK_DonThuoc_BenhNhan");

                    b.Navigation("MaBenhNhanNavigation");
                });

            modelBuilder.Entity("MedRateSystem.Models.PhieuCanhBaoAdr", b =>
                {
                    b.HasOne("MedRateSystem.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("PhieuCanhBaoAdrs")
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK_CanhBao_Thuoc");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("MedRateSystem.Models.PhieuKhaoSat", b =>
                {
                    b.HasOne("MedRateSystem.Models.BenhNhan", "MaBenhNhanNavigation")
                        .WithMany("PhieuKhaoSats")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PhieuKhaoSat_BenhNhan");

                    b.Navigation("MaBenhNhanNavigation");
                });

            modelBuilder.Entity("MedRateSystem.Models.BenhNhan", b =>
                {
                    b.Navigation("PhieuKhaoSats");
                });

            modelBuilder.Entity("MedRateSystem.Models.DonThuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");
                });

            modelBuilder.Entity("MedRateSystem.Models.PhieuKhaoSat", b =>
                {
                    b.Navigation("ChiTietKhaoSats");
                });

            modelBuilder.Entity("MedRateSystem.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietKhaoSats");

                    b.Navigation("PhieuCanhBaoAdrs");
                });
#pragma warning restore 612, 618
        }
    }
}
